# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EamCollector < Formula
  desc "AI usage collector agent for Enterprise Agent Management"
  homepage "https://github.com/AutobahnSecurity/eam-collector"
  version "0.1.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.1/eam-collector-0.1.1-darwin-amd64.tar.gz"
      sha256 "7dfa9685adce6f1a609c3fbccd228cf00a9ff56886b7a0717790e532f5d8feec"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.1/eam-collector-0.1.1-darwin-arm64.tar.gz"
      sha256 "bc64ea237e2bb0a4856ba692968718f9470dc405e9bae0a19ee74f3960c3fafc"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.1/eam-collector-0.1.1-linux-amd64.tar.gz"
      sha256 "a51b188b4cb278814eca1bb09cd2100a082235ee7e9813bbb09bb9a217e234d9"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.1/eam-collector-0.1.1-linux-arm64.tar.gz"
      sha256 "3909586753ff7ee39f39942abfb384e229fb2c3713d402160970f35bf522db8a"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  def post_install
    config_dir = Pathname.new("#{Dir.home}/.eam-collector")
    config_dir.mkpath
    config_file = config_dir/"config.yaml"
    unless config_file.exist?
      cp etc/"eam-collector/config.example.yaml", config_file
      ohai "Config template created at #{config_file}"
      ohai "Edit it with your server URL and API key before starting the service"
    end
  end

  def caveats
    <<~EOS
      To get started:

        1. Edit your config with your EAM server URL and API key:
           nano ~/.eam-collector/config.yaml

        2. Start the background daemon:
           brew services start eam-collector

        3. Check logs:
           tail -f #{var}/log/eam-collector.log
    EOS
  end

  service do
    run [opt_bin/"eam-collector"]
    keep_alive true
    log_path var/"log/eam-collector.log"
    error_log_path var/"log/eam-collector.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eam-collector --version")
  end
end
