# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EamCollector < Formula
  desc "AI usage collector agent for Enterprise Agent Management"
  homepage "https://github.com/AutobahnSecurity/eam-collector"
  version "0.4.3"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.4.3/eam-collector-0.4.3-darwin-amd64.tar.gz"
      sha256 "bc3fe6be6e1db023aa1096e372a65e564b80d0cd4080c1e720c98449c22d88c4"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.4.3/eam-collector-0.4.3-darwin-arm64.tar.gz"
      sha256 "75ccc1b22576d11c9963fc5bd0313adc3309d9f72652694a5da229c33f10e8bf"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.4.3/eam-collector-0.4.3-linux-amd64.tar.gz"
      sha256 "7988dce23531fbff5d2b5d6d070dfb18ae77ac3e14ce5f43e09480914449f283"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.4.3/eam-collector-0.4.3-linux-arm64.tar.gz"
      sha256 "a9995a8dcf0d2c151573ee9e33978a12cda4f459d592a752b9661a3ab83c613e"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  def post_install
    config_dir = Pathname.new("#{Dir.home}/.eam-collector")
    config_dir.mkpath
    config_file = config_dir/"config.yaml"
    unless config_file.exist?
      cp etc/"eam-collector/config.example.yaml", config_file
      ohai "Config template created at #{config_file}"
      ohai "Edit it with your server URL and API key before starting the service"
    end
  end

  def caveats
    <<~EOS
      To get started:

        1. Edit your config with your EAM server URL and API key:
           nano ~/.eam-collector/config.yaml

        2. Start the background daemon:
           brew services start eam-collector

        3. Check logs:
           tail -f #{var}/log/eam-collector.log
    EOS
  end

  service do
    run [opt_bin/"eam-collector"]
    keep_alive true
    log_path var/"log/eam-collector.log"
    error_log_path var/"log/eam-collector.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eam-collector --version")
  end
end
