# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EamCollector < Formula
  desc "AI usage collector agent for Enterprise Agent Management"
  homepage "https://github.com/AutobahnSecurity/eam-collector"
  version "0.1.4"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.4/eam-collector-0.1.4-darwin-amd64.tar.gz"
      sha256 "aa4c033811c22062f47bfafa342b4b153eb608eb69b9523019e6ef179061a1cf"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.4/eam-collector-0.1.4-darwin-arm64.tar.gz"
      sha256 "0946b2c0cee6370f8afb0652efe1fc8082a7049394c6025a4bc9c48eb1653fc2"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.4/eam-collector-0.1.4-linux-amd64.tar.gz"
      sha256 "6e3c1b0161ede886889584a3b701a4c38fd938038c40bfb19f99011379166e31"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.1.4/eam-collector-0.1.4-linux-arm64.tar.gz"
      sha256 "e727053beea01f34c955ea03a1de52d58dee2b200870ce8c16880cb1f52c66f3"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  def post_install
    config_dir = Pathname.new("#{Dir.home}/.eam-collector")
    config_dir.mkpath
    config_file = config_dir/"config.yaml"
    unless config_file.exist?
      cp etc/"eam-collector/config.example.yaml", config_file
      ohai "Config template created at #{config_file}"
      ohai "Edit it with your server URL and API key before starting the service"
    end
  end

  def caveats
    <<~EOS
      To get started:

        1. Edit your config with your EAM server URL and API key:
           nano ~/.eam-collector/config.yaml

        2. Start the background daemon:
           brew services start eam-collector

        3. Check logs:
           tail -f #{var}/log/eam-collector.log
    EOS
  end

  service do
    run [opt_bin/"eam-collector"]
    keep_alive true
    log_path var/"log/eam-collector.log"
    error_log_path var/"log/eam-collector.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eam-collector --version")
  end
end
